[package]
name = "pingpong"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "~0.13", features = [ "wav", "mp3" ] }
belly = { version = "~0.5", git = "https://github.com/jkb0o/belly.git", tag = "v0.5.0"  }
